import { useState } from 'react';
import { Link } from 'react-router-dom';
const T=['Stellt Iech vir','Beruff','Famill','Hobby','Lieblingsessen','Rees','Wunnuert','Problem'];
type M='menu'|'oral'|'listening'|'mock';
export default function SproochentestPracticePage(){const[m,setM]=useState<M>('menu');const[t,setT]=useState('');const[r,setR]=useState(false);const p=()=>T[Math.floor(Math.random()*T.length)];const go=()=>{setT(p());setM('oral');};if(m==='menu')return(<div className="page"><h1 style={{fontFamily:"'Space Grotesk',sans-serif",marginBottom:'1.5rem'}}>Sproochentest Preparation</h1><p style={{color:'#888',marginBottom:'2rem'}}>Practice for Luxembourg citizenship exam. A2 speaking + B1 listening.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(200px,1fr))',gap:'1rem',marginBottom:'2rem'}}><button onClick={go} style={c}>🗣️ Oral Production</button><button onClick={()=>setM('listening')} style={c}>🎧 Listening</button><button onClick={()=>{setT(p());setM('mock');}} style={c}>📝 Mock Exam</button></div><div style={d}><h2 style={{fontSize:'1rem',marginBottom:'0.75rem'}}>Topic Cards</h2>{T.map((x,i)=><div key={i} style={{padding:'0.6rem',background:'#fafafa',borderRadius:8,border:'1px solid #f0f0f0',marginBottom:'0.35rem',fontSize:'0.88rem'}}>{x}</div>)}</div><Link to="/dashboard" style={{color:'#6C5CE7',textDecoration:'none',marginTop:'1rem',display:'inline-block'}}>← Dashboard</Link></div>);if(m==='listening')return(<div className="page"><button onClick={()=>setM('menu')} style={b}>← Back</button><div style={d}><h2>🎧 Listening</h2><p style={{color:'#888',margin:'1rem 0'}}>Audio available once materials uploaded.</p><button onClick={()=>setM('menu')} style={pb}>Back</button></div></div>);return(<div className="page"><div style={{display:'flex',justifyContent:'space-between',marginBottom:'1.5rem'}}><button onClick={()=>setM('menu')} style={b}>← Back</button><span style={{color:'#6C5CE7',fontWeight:700}}>{m==='mock'?'MOCK EXAM':'ORAL'}</span></div><div style={d}><h2 style={{marginBottom:'0.5rem'}}>Topic: {t}</h2><p style={{color:'#888',marginBottom:'1rem'}}>Speak for up to 10 minutes.</p><div style={{display:'flex',gap:'0.75rem'}}><button onClick={()=>setR(!r)} style={{padding:'0.5rem 1rem',background:r?'#6B7280':'#DC2626',color:'#fff',border:'none',borderRadius:10,cursor:'pointer'}}>{r?'Stop':'Record'}</button><button onClick={go} style={{padding:'0.5rem 1rem',background:'#fff',border:'1px solid #eee',borderRadius:10,cursor:'pointer'}}>New Topic</button></div></div></div>);}
const c:React.CSSProperties={background:'#fff',borderRadius:14,padding:'1.25rem',border:'1px solid #f0f0f0',cursor:'pointer',textAlign:'left',fontSize:'0.9rem'};
const d:React.CSSProperties={background:'#fff',borderRadius:14,padding:'1.5rem',border:'1px solid #f0f0f0',marginBottom:'1rem'};
const b:React.CSSProperties={background:'none',border:'none',color:'#6C5CE7',cursor:'pointer',fontWeight:600};
const pb:React.CSSProperties={width:'100%',padding:'0.6rem',background:'#6C5CE7',color:'#fff',border:'none',borderRadius:10,cursor:'pointer',fontWeight:700};
